'use client';

import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Bell, CalendarClock, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Package, ShieldAlert, Star, UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { EmptyState, NotificationRow, PageHeader, Reputation, StatusBadge, UserChip, money } from '@/components/lendup/shared';
import { useDemo } from '@/stores/demo-store';

export function DashboardPage() {
  const { state } = useDemo(); const user = state.users.find((u) => u.id === state.currentUserId)!;
  const myLoans = state.loans.filter((l) => l.borrowerId === user.id || l.lenderId === user.id); const pending = state.requests.filter((r) => r.lenderId === user.id && r.status === 'PENDING').length; const notices = state.notifications.filter((n) => n.userId === user.id).slice(0, 3); const reminders = state.reminders.filter((r) => r.userId === user.id);
  return <><PageHeader eyebrow="Panel personal" title={`Hola, ${user.firstName}`} description="Aquí tienes lo más importante para hoy." action={<Button render={<Link to="/explore" />}>Explorar objetos <ArrowRight /></Button>} />
    <section className="next-action"><div className="next-action-icon"><CalendarClock /></div><div><p className="eyebrow">Tu próxima acción</p><h2>{user.id === 'carlos' ? 'Revisa la devolución anticipada de los libros' : 'Confirma que recibiste el kit de herramientas'}</h2><p>{user.id === 'carlos' ? 'Alexandra espera tu confirmación para liberar la garantía.' : 'Carlos registró la entrega hoy a las 10:02.'}</p></div><Button variant="secondary" render={<Link to={user.id === 'carlos' ? '/loans/ln4' : '/loans/ln1'} />}>Revisar ahora</Button></section>
    <section className="metric-grid"><Metric icon={UsersRound} label="Préstamos activos" value={myLoans.filter((l) => l.status === 'ACTIVE').length} tone="blue" /><Metric icon={Clock3} label="Solicitudes pendientes" value={pending} tone="amber" /><Metric icon={CalendarDays} label="Reservas próximas" value={state.reservations.filter((r) => r.borrowerId === user.id || r.lenderId === user.id).length} tone="teal" /><Metric icon={Package} label="Objetos publicados" value={state.listings.filter((l) => l.ownerId === user.id).length} tone="violet" /><Metric icon={ShieldAlert} label="Incidencias abiertas" value={state.incidents.filter((i) => i.status !== 'RESOLVED').length} tone="rose" /></section>
    <div className="dashboard-columns"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Actividad</span><h2>Próximos eventos</h2></div><Link to="/calendar">Ver calendario</Link></div><div className="event-list"><Event date="27" month="SEP" title="Entrega · Cámara Sony a6400" meta="14:00 · UPC Monterrico" type="Entrega" /><Event date="28" month="SEP" title="Devolución · Kit de herramientas" meta="17:00 · Puerta 3 UNI" type="Devolución" /><Event date="12" month="OCT" title="Devolución · Cámara Sony a6400" meta="18:00 · UPC Monterrico" type="Devolución" /></div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Eventos ocurridos</span><h2>Notificaciones recientes</h2></div><Link to="/notifications">Ver todas</Link></div>{notices.map((n) => <Link key={n.id} to={n.href}><NotificationRow title={n.title} message={n.message} time={n.createdAt} unread={!n.read} /></Link>)}</section></div>
    <section className="panel reminders-panel"><div className="section-heading"><div><span className="eyebrow">Antes de que ocurra</span><h2>Próximos recordatorios</h2></div></div><div className="reminder-grid">{reminders.map((r) => <Link key={r.id} to={r.href}><NotificationRow reminder title={r.title} message={r.kind === 'RETURN' ? 'Ten listo el objeto y registra evidencias finales.' : 'Tienes una acción pendiente en esta operación.'} time={r.dueAt} /></Link>)}</div></section>
  </>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof UsersRound; label: string; value: number; tone: string }) { return <article className="metric-card"><span className={`metric-icon ${tone}`}><Icon /></span><div><strong>{value}</strong><span>{label}</span></div></article>; }
function Event({ date, month, title, meta, type }: { date: string; month: string; title: string; meta: string; type: string }) { return <article className="event-row"><span className="event-date"><strong>{date}</strong><small>{month}</small></span><div><strong>{title}</strong><p>{meta}</p></div><span className="event-type">{type}</span></article>; }

export function NotificationsPage() {
  const { state, markNotification } = useDemo(); const userId = state.currentUserId; const notifications = state.notifications.filter((n) => n.userId === userId); const reminders = state.reminders.filter((r) => r.userId === userId);
  return <><PageHeader eyebrow="Actividad" title="Notificaciones y recordatorios" description="Los eventos ocurridos y las obligaciones próximas se muestran por separado." action={<Button variant="outline" onClick={() => markNotification()}>Marcar todas como leídas</Button>} /><div className="two-panel-grid"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Ya ocurrió</span><h2>Notificaciones</h2></div><Bell /></div>{notifications.length ? notifications.map((n) => <Link to={n.href} key={n.id} onClick={() => markNotification(n.id)}><NotificationRow title={n.title} message={n.message} time={n.createdAt} unread={!n.read} /></Link>) : <EmptyState title="Estás al día" description="No tienes notificaciones nuevas." />}</section><section className="panel reminders-side"><div className="section-heading"><div><span className="eyebrow">Próximas obligaciones</span><h2>Recordatorios</h2></div><CalendarClock /></div>{reminders.map((r) => <Link to={r.href} key={r.id}><NotificationRow reminder title={r.title} message="Abre la operación para consultar todos los detalles." time={r.dueAt} /></Link>)}</section></div></>;
}

const days = Array.from({ length: 35 }, (_, index) => index < 3 ? null : index - 2);
export function CalendarPage() {
  return <><PageHeader eyebrow="Tu agenda" title="Calendario" description="Entregas, devoluciones, reservas y recordatorios en un solo lugar." action={<div className="calendar-actions"><Button variant="outline" size="icon"><ChevronLeft /></Button><Button variant="outline">Septiembre 2026</Button><Button variant="outline" size="icon"><ChevronRight /></Button></div>} /><section className="panel calendar-panel"><div className="calendar-toolbar"><div className="segmented"><button className="active">Mes</button><button>Semana</button></div><div className="calendar-legend"><span className="delivery">Entrega</span><span className="return">Devolución</span><span className="reminder-dot">Recordatorio</span></div></div><div className="calendar-grid"><div>Lun</div><div>Mar</div><div>Mié</div><div>Jue</div><div>Vie</div><div>Sáb</div><div>Dom</div>{days.map((day, index) => <div key={index} className={`calendar-day ${day === 26 ? 'today' : ''}`}>{day && <span>{day}</span>}{day === 24 && <Link to="/loans/ln2" className="cal-event delivery">Entrega · Cámara</Link>}{day === 26 && <Link to="/loans/ln1" className="cal-event reminder-event">Confirmar recepción</Link>}{day === 28 && <Link to="/loans/ln1" className="cal-event return">Devolución · Kit</Link>}{day === 30 && <Link to="/loans/ln4" className="cal-event return">Fecha original · Libros</Link>}</div>)}</div></section></>;
}

export function TransactionsPage() {
  const { state } = useDemo(); const rows = state.transactions.filter((t) => t.userId === state.currentUserId);
  return <><PageHeader eyebrow="Actividad económica" title="Transacciones" description="Tarifas, garantías, liberaciones y afectaciones se mantienen siempre separadas." /><section className="panel table-panel"><div className="table-tools"><div className="transaction-summary"><CircleDollarSign /><span><strong>{money(rows.reduce((total, row) => total + row.amount, 0))}</strong><small>movimientos registrados</small></span></div><Button variant="outline">Descargar resumen</Button></div><div className="responsive-table"><table><thead><tr><th>Fecha</th><th>Préstamo</th><th>Tipo</th><th>Monto</th><th>Medio</th><th>Estado</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.date}</td><td><Link to={`/loans/${row.loanId}`}>{row.loanId.toUpperCase()}</Link></td><td>{row.type}</td><td><strong>{money(row.amount)}</strong></td><td>{row.method}</td><td><StatusBadge status={row.status.toUpperCase().replaceAll(' ', '_')} /></td></tr>)}</tbody></table></div></section></>;
}

export function ProfilePage() { const { state, logout } = useDemo(); const user = state.users.find((u) => u.id === state.currentUserId)!; return <><PageHeader eyebrow="Cuenta" title="Mi perfil" description="Tu identidad universitaria y reputación en LendUp." /><ProfileContent user={user} own /><div className="profile-actions"><Button variant="outline">Editar perfil</Button><Button variant="ghost" onClick={logout}>Cerrar sesión</Button></div></>; }
export function PublicProfilePage() { const { id } = useParams(); const { state } = useDemo(); const user = state.users.find((u) => u.id === id); if (!user) return <EmptyState title="Perfil no encontrado" description="Este perfil no está disponible." />; return <><PageHeader eyebrow="Perfil público" title={user.name} description="Información verificada y reputación dentro de la comunidad." /><ProfileContent user={user} /></>; }
function ProfileContent({ user, own = false }: { user: ReturnType<typeof useDemo>['state']['users'][number]; own?: boolean }) { return <div className="profile-grid"><section className="panel profile-card"><span className="profile-avatar">{user.initials}</span><h2>{user.name}</h2><p>{user.career} · {user.cycle}</p><div className="profile-badges"><span><CheckCircle2 />Correo verificado</span><span><CheckCircle2 />{user.university} · {user.campus}</span></div>{own && <p className="private-note">Tu teléfono y correo no se muestran en el perfil público.</p>}</section><section className="panel reputation-card"><span className="eyebrow">Reputación</span><div className="rating-large"><Star fill="currentColor" /><strong>{user.rating}</strong><span>/ 5</span></div><p>{user.completedLoans} préstamos completados</p><div className="rating-bars">{[5,4,3,2,1].map((n) => <div key={n}><span>{n}</span><div><i style={{ width: `${n === 5 ? 82 : n === 4 ? 14 : 2}%` }} /></div></div>)}</div></section><section className="panel reviews-card"><span className="eyebrow">Comentarios recientes</span><h2>Experiencias de la comunidad</h2><blockquote>“Todo estuvo coordinado y el objeto se entregó exactamente como se describía.”<footer><UserChip user={user} /><Reputation value={5} /></footer></blockquote><blockquote>“Respondió rápido y cuidó muy bien el equipo durante el préstamo.”<footer><span>Usuario verificado</span><Reputation value={4.8} /></footer></blockquote></section></div>; }
